### PR TITLE
Make XENGPUMiner work on macOS with OpenCL

### PR DESCRIPTION
**Pull request by ludolphus**
Added some includes and updates to make files to allow build on macOS (tested on 13.5.x).

### CODE REVIEW

**Review by shanhaicoder — APPROVED** [review]
Really cool, thanks for macOS support

**Comment by steventswu** [comment]
> Added some includes and updates to make files to allow build on macOS (tested on 13.5.x).

Is it possible to have a guide on how to set it up for mac? Will be really nice to have.

**Comment by ludolphus** [comment]
> > Added some includes and updates to make files to allow build on macOS (tested on 13.5.x).
> 
> Is it possible to have a guide on how to set it up for mac? Will be really nice to have.

You need to have at least XCode and cmake installed. To install cmake use:

`brew install cmake`

But although it all compiles and links, the gpu miner does not seem to work. When printing out generated hashed, they are all the same. If someone has an idea, please update the code. To print hashed uncomment line 158 in cudaexecutive.cpp

Another issue is that the command line arguments do seem to get used. The code set the batch size to 0 and should be overriden by argument `-b 1024`. To test with 1024 batch size change line 64 in processingunit.h:

`    std::size_t getBatchSize() const { return 1024; }`

And yet another thing is that it runs with CUDA instead of OpenCL. There is a command line argument `-m opencl` to specify using OpenCL, but this also does not work.

So, to make the miner run on macOS needs some more work..

**Comment by xzone911** [comment]
./xengpuminer -b 1024
dyld[18773]: Symbol not found: _argon2_ctx_mem
  Referenced from: <382D0DB8-9BBF-397F-84F9-BA30C2622F54> /Users/wengmengxian/PycharmProjects/python/XENGPUMiner/xengpuminer
  Expected in:     <54825AF0-4A11-3C2F-989C-0D860820CE40> /opt/homebrew/Cellar/argon2/20190702_1/lib/libargon2.1.dylib
[1]    18773 abort      ./xengpuminer -b 1024

**Comment by steventswu** [comment]
> > > Added some includes and updates to make files to allow build on macOS (tested on 13.5.x).
> > 
> > 
> > Is it possible to have a guide on how to set it up for mac? Will be really nice to have.
> So, to make the miner run on macOS needs some more work..

Thanks Steven for the reply! Really appreciated.
I installed `cmake`with brew and did run with the `-m opencl` argument, but doesn't seem like the code read this argument. `Using Device #0:` does not output anything. 
Hopefully the code can get updated version for mac to work.

**Pull request merged**
